name: Fetch Note Articles

on:
  schedule:
    # 毎日日本時間の6時と18時に実行 (UTC 21:00と09:00)
    - cron: '0 21 * * *'
    - cron: '0 9 * * *'
  workflow_dispatch: # 手動実行も可能

jobs:
  fetch-articles:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Fetch Note articles
        run: node scripts/fetchNoteRss.mjs
        env:
          NODE_ENV: production
      
      - name: Build project to update dist folder
        run: npm run build
      
      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code public/note-articles.json dist/note-articles.json || echo "changed=true" >> $GITHUB_OUTPUT
      
      - name: Commit and push if changed
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/note-articles.json dist/
          git commit -m "Update Note articles [skip ci]"
          git push